site_name: Documentation
theme:
  name: material
nav:
  - Home: index.md
  - xf8bot:
    - Contributors: xf8bot/contributors.md
    - Documentation: xf8bot/index.md
    - Commands: xf8bot/commands.md
    - Startup Guide: xf8bot/startup.md
  - License: LICENSE.md